### PR TITLE
Pull Request #1: adding JSON-RPC scraping scripts and python scripts for use in pyspark

### PR DESCRIPTION
**Pull request by testaccountdx**
Added JSON-RPC scraping scripts (data scraping is complete and loaded into S3)

Added python scripts for use in pyspark (still work in progress, need to revise scripts to generate correct RDD and/or DataFrame objects in spark context).

Need to add configuration and secret files in accordance with best practices.

### CODE REVIEW

**Review by bluerider — CHANGES_REQUESTED** [review]
Encapsulate your main functions in an actual function. Your boiler plate main code should just call main().

**Review by testaccountdx — COMMENTED** [review]
Addressed

**Comment by testaccountdx** [comment]
Addressed comments from previous pull request, in addition to adding new files / changes to address the following:
1) remove any credentials / sensitive information (all handled in separate config files that are NOT committed to Github)
2) refactored core Spark scripts (.py files under src/spark directory) to encapsulate functions and kick things off with a __main__ function
3) documentation (i.e., README files) are not quite 100% there yet, but created README.md placeholders in appropriate folders
4) added files for frontend UI (i.e., website) in frontend directory - removed any mention of credentials / sensitive information here too

**Review by testaccountdx — COMMENTED** [review]
Encapsulated functions

**Pull request merged**
